### PR TITLE
added cobertura output

### LINKED ISSUE #123: get coverage shield working
wasn't able to get it working here #118 / #120 .  Basically looking to get corbetura coverage output, which is needed for the shield.
http://www.thegreenhouse.io:8080/view/Open%20Source/job/MASTER-github-dashboard/ws/reports/test-coverage/

### PR DESCRIPTION
**Pull request by thescientist13**
resolves #123

### CODE REVIEW

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
Coverage is showing up in master now after running a build against the master job
http://www.thegreenhouse.io:8080/job/MASTER-github-dashboard/17/
screen shot 2017-03-21 at 9 32 01 pm

**Comment by thescientist13** [comment]
thanks for pointing me in the right direction @jpoo

**Comment by jpoo90** [comment]
Awesome, glad you figured it out 🎉

**Pull request merged**
