### PR TITLE
Mocked credentials for testing purposes

### LINKED ISSUE #149: When running the tests console shows UNHANDLED_ERROR in the logs
```
UNHANDLED ERROR { Error: Request failed with status code 404
        at createErrorResponse (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/utils.js:87:15)
        at Object.settle (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/utils.js:67:16)
        at handleRequest (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/handle_request.js:53:11)
        at /Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/index.js:16:9
        at MockAdapter.<anonymous> (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/index.js:15:14)
        at dispatchRequest (/Users/jp/Documents/github-dashboard/node_modules/axios/lib/core/dispatchRequest.js:52:10)
        at process._tickCallback (internal/process/next_tick.js:103:7)
```

I was able to narrow down the issue to `bootstrap.spec.jsx`. When this suit runs, multiple errors like the one above appear. I'll give it a try to see if I'm able to solve it.

### PR DESCRIPTION
**Pull request by jpoo90**
Closes #149 

* Added a mock for the credentials module. 
* Removed hardcoded credentials from `bootstrap.spec.jsx`

### CODE REVIEW

**Comment by thescientist13** [comment]
@jpoo90 
There is a mock credentials class in _test/mocks_, would that be sufficient rather than making the new file?
https://github.com/thescientist13/github-dashboard/blob/master/test/mocks/user-credentials.json

**Comment by jpoo90** [comment]
@thescientist13 I don't think so. In the `bootstrap.tsx` we need to mock the module itself. https://github.com/thescientist13/github-dashboard/blob/master/src/components/bootstrap/bootstrap.tsx#L29

`test/mocks` has a json with the credentials. In that case, we would need to mock the module, import the `user-credentials.json` and then return the json from the module mock. 

Maybe I'm missing something from the mocking structure you have in place. But I think it's easier to mock the module itself and re-use when necessary.

**Comment by thescientist13** [comment]
@jpoo90 
I see what you mean. 

So could we move _credentials.ts_  to _test/mocks_?  Maybe _user-credentials.json_ should be deprecated then? (depending on its usage in the app)

**Comment by jpoo90** [comment]
@thescientist13 

We _can't_ move the mock to `test/mocks`. There as an [open discussion](https://github.com/facebook/jest/issues/2726) in Jest's repo about it. I agree that we can depreacte user-credentials.json and use the mock module instead. 

If you are OK with having the mock folder, I can replace use it to replace `user-credentials.json`

**Comment by thescientist13** [comment]
> We can't move the mock to test/mocks. There as an open discussion in Jest's repo about it.

Well, I guess that settles that then.

> If you are OK with having the __mock__ folder, I can replace use it to replace user-credentials.json

Sounds like a plan!  👍

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
Looks like we may need to add a spec for `credentials.ts`?  I think adding it may have caused the overall coverage to do down, unless it can be ignored?
http://www.thegreenhouse.io:8080/job/CI-github-dashboard/145/console
```bash
18:43:35 Cobertura coverage report found.
18:43:35 Code coverage enforcement failed for the following metrics:
18:43:35     Methods's stability is 83.33 and set mininum stability is 87.5.
18:43:35     Lines's stability is 89.49 and set mininum stability is 93.09.
18:43:35 Setting Build to unstable.
```

**Comment by thescientist13** [comment]
SOOOOOOOO close
```
19:46:08 Code coverage enforcement failed for the following metrics:
19:46:08     Methods's stability is 86.46 and set mininum stability is 87.5.
19:46:08     Lines's stability is 92.49 and set mininum stability is 93.09.
```

**Comment by jpoo90** [comment]
@thescientist13 

I can't find why the coverage dropped. This is the difference between master and this branch.

Master:
master

PR:
pullrequest

Do you have any recommendations ? I don't see how the updated mock affected the interface coverage :unamused:

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
Can one of the admins verify this patch?

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
Can one of the admins verify this patch?

**Comment by thescientist13** [comment]
Can one of the admins verify this patch?

**Comment by thescientist13** [comment]
@jpoo90 
i fine tuned the metric targets for Cobertura to set thresholds instead of auto update.  Not sure why but looks good to me.

fyi: merge conflict

**Comment by jpoo90** [comment]
@thescientist13 Solved merge conflicts

**Pull request merged**
